version: '3.4'

services:
  
  spotlist.api:
    container_name: spotlist.api
    depends_on: 
    - spotlist.db
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://spotlist.db:27017
      - MONGO_DAILYTRENDS_DB=daily-trends
      - MONGO_FEEDS_COLLECTION_NAME=feeds
      - API_PORT=8080
      - UPDATE_ALL_FEEDS_CRON_TIME_JOB=00 00 6 * * *
  
  spotlist.db:
    container_name: spotlist.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db